#!/usr/bin/env python3
"""Generate fully-pinned requirements-{runtime,dev}.lock from pyproject.toml.

pyproject.toml is the single source of truth for WHAT the project depends on
(CI installs straight from it with `pip install -e ".[dev]"`). The *.in files
are derived from it, and the *.lock files are the full transitive closure
(resolved by pip-compile) with cross-platform hashes, so `docker build` is
reproducible:

    pyproject.toml  ->  requirements-{runtime,dev}.in   (top-level, derived)
    requirements-*.in  ->  requirements-*.lock          (pinned + hashed)

The runtime lock (installed by the image) also carries `--require-hashes`, so a
hand-added hashless line fails the install instead of silently weakening the
reproducibility guarantee. The dev lock pins pip/setuptools/wheel via
`--allow-unsafe` (pip-tools pulls them in as build deps).

Usage:
    python scripts/gen-requirements.py              # (re)write .in + .lock
    python scripts/gen-requirements.py --check      # offline drift check
    python scripts/gen-requirements.py --selftest   # run embedded fixtures
    python scripts/gen-requirements.py --root DIR   # operate on DIR (tests/CI)

`--check` is OFFLINE (no pip-compile, no network): it verifies the *.in files
still match pyproject.toml and that each *.lock is present, fully `==`-pinned,
hashed, and `--require-hashes`-guarded. Regeneration (`make deps`) is a
deliberate step that re-resolves against PyPI; the committed lock is a frozen
snapshot — that freezing is exactly what makes the image reproducible.

Exit: 0 ok, 1 drift/stale/--check failure or selftest failure, 2 config error.
"""

from __future__ import annotations

import argparse
import difflib
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

RUNTIME_IN = "requirements-runtime.in"
DEV_IN = "requirements-dev.in"
RUNTIME_LOCK = "requirements-runtime.lock"
DEV_LOCK = "requirements-dev.lock"

_IN_HEADER = "# GENERATED by scripts/gen-requirements.py — do not edit by hand.\n"
RUNTIME_IN_HEADER = _IN_HEADER + "# Source of truth: pyproject.toml [project].dependencies\n"
DEV_IN_HEADER = (
    _IN_HEADER
    + "# Source of truth: pyproject.toml [project.optional-dependencies].dev\n"
    + "# Constrained by the runtime lock so shared deps resolve consistently.\n"
)


def derive_ins(pyproject: dict) -> dict[str, str]:
    """Map .in filename -> rendered content for a parsed pyproject dict."""
    project = pyproject["project"]
    runtime = list(project.get("dependencies", []))
    dev = list((project.get("optional-dependencies") or {}).get("dev", []))
    return {
        RUNTIME_IN: RUNTIME_IN_HEADER + "".join(f"{d}\n" for d in runtime),
        DEV_IN: DEV_IN_HEADER + "-c requirements-runtime.lock\n" + "".join(f"{d}\n" for d in dev),
    }


def read_pyproject(root: Path) -> dict:
    path = root / "pyproject.toml"
    if not path.exists():
        raise FileNotFoundError(f"{path} not found")
    with open(path, "rb") as fh:
        return tomllib.load(fh)


def _diff(actual: str, expected: str, name: str) -> str:
    return "\n".join(
        difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=f"a/{name}",
            tofile=f"b/{name}",
            lineterm="",
        )
    )


def pinned_issues(content: str, name: str) -> list[str]:
    """Structural reproducibility checks on a lock file (offline, no network)."""
    issues: list[str] = []
    if name == RUNTIME_LOCK and "--require-hashes" not in content:
        issues.append(f"{name}: missing --require-hashes guard")
    if "autogenerated by pip-compile" not in content:
        issues.append(f"{name}: missing pip-compile header (was it hand-edited?)")
    for i, line in enumerate(content.splitlines(), 1):
        s = line.strip()
        if not s or s.startswith("#") or s.startswith(("--", "-c ", "-r ", "-e ")):
            continue
        if s[0].isalpha() and "==" not in s:
            issues.append(f"{name}:{i}: unpinned requirement: {s}")
    return issues


def _compile(root: Path) -> None:
    """Resolve each .in to a .lock with pip-compile (requires pip-tools + network)."""
    for lock, inp in ((RUNTIME_LOCK, RUNTIME_IN), (DEV_LOCK, DEV_IN)):
        cmd = [
            sys.executable,
            "-m",
            "piptools",
            "compile",
            "--no-strip-extras",
            "--generate-hashes",
            "--quiet",
        ]
        if lock == DEV_LOCK:
            cmd.append("--allow-unsafe")  # pin pip/setuptools/wheel that pip-tools pulls in
        # Relative -o/in paths (cwd=root) so no machine literals reach the header.
        cmd += ["-o", lock, inp]
        subprocess.run(cmd, cwd=root, check=True)
        print(f"[gen-requirements] resolved {inp} -> {lock}")


def _guard_runtime_hashes(root: Path) -> None:
    """Prepend the --require-hashes guard to the runtime lock (the image's lock)."""
    path = root / RUNTIME_LOCK
    content = path.read_text(encoding="utf-8")
    if not content.startswith("--require-hashes\n"):
        path.write_text("--require-hashes\n" + content, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="offline drift check")
    parser.add_argument("--selftest", action="store_true", help="run embedded fixtures")
    parser.add_argument("--root", type=Path, default=None, help="repo root override")
    args = parser.parse_args(argv)

    if args.selftest:
        return _selftest()

    root = (args.root or Path(__file__).resolve().parents[1]).resolve()
    try:
        pyproject = read_pyproject(root)
    except FileNotFoundError as e:
        print(f"[gen-requirements] FAIL: {e}", file=sys.stderr)
        return 2

    ins = derive_ins(pyproject)
    if args.check:
        rc = 0
        for name, content in ins.items():
            path = root / name
            if not path.exists():
                print(f"[gen-requirements] FAIL: {name} missing — run make deps", file=sys.stderr)
                rc = 1
                continue
            actual = path.read_text(encoding="utf-8")
            if actual != content:
                print(f"[gen-requirements] FAIL: {name} drifted from pyproject.toml:", file=sys.stderr)
                print(_diff(actual, content, name), file=sys.stderr)
                print("  -> regenerate with: make deps", file=sys.stderr)
                rc = 1
        for name in (RUNTIME_LOCK, DEV_LOCK):
            path = root / name
            if not path.exists():
                print(f"[gen-requirements] FAIL: {name} missing — run make deps", file=sys.stderr)
                rc = 1
                continue
            for issue in pinned_issues(path.read_text(encoding="utf-8"), name):
                print(f"[gen-requirements] FAIL: {issue}", file=sys.stderr)
                rc = 1
        if rc == 0:
            print("[gen-requirements] clean — .in match pyproject.toml; locks fully pinned + hashed")
        return rc

    for name, content in ins.items():
        (root / name).write_text(content, encoding="utf-8")
        print(f"[gen-requirements] wrote {name}")
    _compile(root)
    _guard_runtime_hashes(root)
    print("[gen-requirements] wrote --require-hashes guard to the runtime lock")
    return 0


# --- embedded fixtures (no network, no pip-compile) -------------------------
def _selftest() -> int:
    fail = 0

    def check(cond: bool, msg: str) -> None:
        nonlocal fail
        if not cond:
            print(f"[gen-requirements] selftest FAIL: {msg}")
            fail += 1

    # 1. .in derivation from pyproject.
    py = {
        "project": {
            "dependencies": ["fastapi==1.0.0", "uvicorn[standard]==2.0.0"],
            "optional-dependencies": {"dev": ["pytest==9.0.0", "ruff==0.9.0"]},
        }
    }
    ins = derive_ins(py)
    check(
        ins[RUNTIME_IN].splitlines()[-2:] == ["fastapi==1.0.0", "uvicorn[standard]==2.0.0"],
        "runtime .in content wrong",
    )
    check(
        ins[DEV_IN].splitlines()[-2:] == ["pytest==9.0.0", "ruff==0.9.0"],
        "dev .in content wrong",
    )
    check(ins[DEV_IN].startswith(_IN_HEADER) and "-c requirements-runtime.lock" in ins[DEV_IN], "dev .in missing -c constraint")

    # 2. lock structural checks.
    good_lock = (
        "--require-hashes\n"
        "#\n"
        "# This file is autogenerated by pip-compile with Python 3.12\n"
        "#\n"
        "fastapi==1.0.0 \\\n    --hash=sha256:abcd\n"
    )
    check(pinned_issues(good_lock, RUNTIME_LOCK) == [], "valid lock flagged")
    check(
        "unpinned requirement" in "\n".join(pinned_issues("fastapi>=1.0.0\n", RUNTIME_LOCK)),
        "unpinned requirement not flagged",
    )
    check(
        any("missing --require-hashes" in i for i in pinned_issues("fastapi==1.0.0\n", RUNTIME_LOCK)),
        "missing --require-hashes not flagged",
    )
    check(
        any("missing pip-compile header" in i for i in pinned_issues("--require-hashes\nfastapi==1.0.0\n", RUNTIME_LOCK)),
        "missing header not flagged",
    )
    # The dev lock is hash-verified but not --require-hashes-guarded (it pins
    # pip/setuptools via --allow-unsafe), so its absence there is not drift.
    check(
        not any("missing --require-hashes" in i for i in pinned_issues("fastapi==1.0.0\n", DEV_LOCK)),
        "dev lock incorrectly requires --require-hashes",
    )

    # 3. offline --check end-to-end.
    with tempfile.TemporaryDirectory(prefix="gen-req-") as tmp:
        root = Path(tmp)
        (root / "pyproject.toml").write_text(
            "[project]\n"
            'dependencies = ["fastapi==1.0.0", "uvicorn[standard]==2.0.0"]\n'
            "[project.optional-dependencies]\n"
            'dev = ["pytest==9.0.0", "ruff==0.9.0"]\n',
            encoding="utf-8",
        )
        for name, content in derive_ins(read_pyproject(root)).items():
            (root / name).write_text(content, encoding="utf-8")
        for name in (RUNTIME_LOCK, DEV_LOCK):
            (root / name).write_text(good_lock, encoding="utf-8")
        check(main(["--root", str(root), "--check"]) == 0, "--check failed on a clean tree")

        # Drift the runtime .in -> --check exit 1.
        (root / RUNTIME_IN).write_text(_IN_HEADER + "fastapi==1.0.0\n", encoding="utf-8")
        check(main(["--root", str(root), "--check"]) == 1, "--check passed on a drifted .in")

        # Restore, then unpin a lock -> --check exit 1.
        for name, content in derive_ins(read_pyproject(root)).items():
            (root / name).write_text(content, encoding="utf-8")
        (root / RUNTIME_LOCK).write_text("--require-hashes\nfastapi>=1.0.0\n", encoding="utf-8")
        check(main(["--root", str(root), "--check"]) == 1, "--check passed on an unpinned lock")

        # Missing pyproject -> exit 2.
        check(main(["--root", str(root / "nope"), "--check"]) == 2, "missing pyproject did not exit 2")

    if fail == 0:
        print("[gen-requirements] selftest PASS")
        return 0
    print(f"[gen-requirements] selftest FAIL ({fail} check(s))")
    return 1


if __name__ == "__main__":
    sys.exit(main())
