#!/usr/bin/env python3
"""Generate fully-pinned requirements-{runtime,dev}.lock from pyproject.toml.

pyproject.toml is the single source of truth for WHAT the project depends on
(CI installs straight from it with `pip install -e ".[dev]"`). The *.lock files
are the full transitive closure (resolved by pip-compile) with cross-platform
hashes, so `docker build` is reproducible:

    pyproject.toml  ->  (transient requirements-*.in)  ->  requirements-*.lock

The *.in files are NOT committed: they are pure intermediates written on the
fly during generation. Committing them made GitHub's dependency-graph updater
(Dependabot) treat the repo as a pip-compile project and fail on the dev .in's
`-c requirements-runtime.lock` constraint. pyproject.toml is the only
human-edited dependency file.

The runtime lock (installed by the image) carries `--require-hashes`, so a
hand-added hashless line fails the install instead of silently weakening the
reproducibility guarantee. The dev lock pins pip/setuptools/wheel via
`--allow-unsafe` (pip-tools pulls them in as build deps).

Usage:
    python scripts/gen-requirements.py              # (re)write .lock files
    python scripts/gen-requirements.py --check      # offline drift check
    python scripts/gen-requirements.py --selftest   # run embedded fixtures
    python scripts/gen-requirements.py --root DIR   # operate on DIR (tests/CI)

`--check` is OFFLINE (no pip-compile, no network): it verifies each lock is
present, fully `==`-pinned, hashed, `--require-hashes`-guarded (runtime), and
that each lock's DIRECT dependencies still match pyproject.toml. Regeneration
(`make deps`) is a deliberate step that re-resolves against PyPI; the committed
lock is a frozen snapshot — that freezing is exactly what makes the image
reproducible.

Exit: 0 ok, 1 drift/stale/--check failure or selftest failure, 2 config error.
"""

from __future__ import annotations

import argparse
import difflib
import re
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

RUNTIME_IN = "requirements-runtime.in"
DEV_IN = "requirements-dev.in"
RUNTIME_LOCK = "requirements-runtime.lock"
DEV_LOCK = "requirements-dev.lock"

_IN_HEADER = "# GENERATED by scripts/gen-requirements.py — do not edit by hand.\n"
RUNTIME_IN_HEADER = _IN_HEADER + "# Source of truth: pyproject.toml [project].dependencies\n"
DEV_IN_HEADER = (
    _IN_HEADER
    + "# Source of truth: pyproject.toml [project.optional-dependencies].dev\n"
    + "# Constrained by the runtime lock so shared deps resolve consistently.\n"
)

# A package line in a pip-compile lock: name[extra]==version [; markers] \
_DIRECT_RE = re.compile(r"^([A-Za-z0-9_.\-]+(?:\[[^\]]+\])?==[^ ;\\]+)")


def deps(pyproject: dict) -> tuple[list[str], list[str]]:
    """Return (runtime, dev) top-level dependency specifiers from pyproject."""
    project = pyproject["project"]
    runtime = list(project.get("dependencies", []))
    dev = list((project.get("optional-dependencies") or {}).get("dev", []))
    return runtime, dev


def in_contents(runtime: list[str], dev: list[str]) -> dict[str, str]:
    """Transient *.in contents (top-level, plus a runtime constraint on dev)."""
    return {
        RUNTIME_IN: RUNTIME_IN_HEADER + "".join(f"{d}\n" for d in runtime),
        DEV_IN: DEV_IN_HEADER + "-c requirements-runtime.lock\n" + "".join(f"{d}\n" for d in dev),
    }


def read_pyproject(root: Path) -> dict:
    path = root / "pyproject.toml"
    if not path.exists():
        raise FileNotFoundError(f"{path} not found")
    with open(path, "rb") as fh:
        return tomllib.load(fh)


def direct_specs(content: str, in_name: str) -> list[str]:
    """Direct (top-level) requirement specifiers in a pip-compile lock.

    A package is direct iff its `# via` annotation references the .in file
    (single-line `# via -r X.in` or the multi-line form under `# via`).
    """
    specs: list[str] = []
    current: str | None = None
    comments: list[str] = []
    for line in content.splitlines():
        s = line.strip()
        m = _DIRECT_RE.match(s)
        if m:
            if current is not None and f"-r {in_name}" in " ".join(comments):
                specs.append(current)
            current = m.group(1)
            comments = []
        elif s.startswith("#"):
            comments.append(s.lstrip("#").strip())
    if current is not None and f"-r {in_name}" in " ".join(comments):
        specs.append(current)
    return specs


def norm(spec: str) -> str:
    """Normalize a specifier for pyproject-vs-lock comparison.

    Lowercases the name (PyYAML -> pyyaml), folds _ to -, and DROPS extras
    (httpx[http2]==0.28.1 -> httpx==0.28.1): a transitive dep can merge an
    extra into a bare direct pin, which is correct resolution, not drift.
    """
    name, sep, rest = spec.partition("==")
    if not sep:
        return spec.lower()
    return name.split("[", 1)[0].lower().replace("_", "-") + sep + rest


def _diff(actual: str, expected: str, name: str) -> str:
    return "\n".join(
        difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=f"a/{name}",
            tofile=f"b/{name}",
            lineterm="",
        )
    )


def pinned_issues(content: str, name: str) -> list[str]:
    """Structural reproducibility checks on a lock file (offline, no network)."""
    issues: list[str] = []
    if name == RUNTIME_LOCK and "--require-hashes" not in content:
        issues.append(f"{name}: missing --require-hashes guard")
    if "autogenerated by pip-compile" not in content:
        issues.append(f"{name}: missing pip-compile header (was it hand-edited?)")
    for i, line in enumerate(content.splitlines(), 1):
        s = line.strip()
        if not s or s.startswith("#") or s.startswith(("--", "-c ", "-r ", "-e ")):
            continue
        if s[0].isalpha() and "==" not in s:
            issues.append(f"{name}:{i}: unpinned requirement: {s}")
    return issues


def _compile(root: Path) -> None:
    """Resolve each transient .in to a .lock with pip-compile (needs pip-tools)."""
    for lock, inp in ((RUNTIME_LOCK, RUNTIME_IN), (DEV_LOCK, DEV_IN)):
        cmd = [
            sys.executable,
            "-m",
            "piptools",
            "compile",
            "--no-strip-extras",
            "--generate-hashes",
            "--quiet",
        ]
        if lock == DEV_LOCK:
            cmd.append("--allow-unsafe")  # pin pip/setuptools/wheel that pip-tools pulls in
        # Relative -o/in paths (cwd=root) so no machine literals reach the header.
        cmd += ["-o", lock, inp]
        subprocess.run(cmd, cwd=root, check=True)
        print(f"[gen-requirements] resolved {inp} -> {lock}")


def _guard_runtime_hashes(root: Path) -> None:
    """Prepend the --require-hashes guard to the runtime lock (the image's lock)."""
    path = root / RUNTIME_LOCK
    content = path.read_text(encoding="utf-8")
    if not content.startswith("--require-hashes\n"):
        path.write_text("--require-hashes\n" + content, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="offline drift check")
    parser.add_argument("--selftest", action="store_true", help="run embedded fixtures")
    parser.add_argument("--root", type=Path, default=None, help="repo root override")
    args = parser.parse_args(argv)

    if args.selftest:
        return _selftest()

    root = (args.root or Path(__file__).resolve().parents[1]).resolve()
    try:
        pyproject = read_pyproject(root)
    except FileNotFoundError as e:
        print(f"[gen-requirements] FAIL: {e}", file=sys.stderr)
        return 2

    runtime_deps, dev_deps = deps(pyproject)
    if args.check:
        rc = 0
        for lock, in_name, expected in (
            (RUNTIME_LOCK, RUNTIME_IN, runtime_deps),
            (DEV_LOCK, DEV_IN, dev_deps),
        ):
            path = root / lock
            if not path.exists():
                print(f"[gen-requirements] FAIL: {lock} missing — run make deps", file=sys.stderr)
                rc = 1
                continue
            content = path.read_text(encoding="utf-8")
            for issue in pinned_issues(content, lock):
                print(f"[gen-requirements] FAIL: {issue}", file=sys.stderr)
                rc = 1
            actual = {norm(s) for s in direct_specs(content, in_name)}
            wanted = {norm(s) for s in expected}
            if actual != wanted:
                print(f"[gen-requirements] FAIL: {lock} direct deps drifted from pyproject.toml:", file=sys.stderr)
                for s in sorted(wanted - actual):
                    print(f"  missing in lock: {s}", file=sys.stderr)
                for s in sorted(actual - wanted):
                    print(f"  extra in lock:   {s}", file=sys.stderr)
                print("  -> regenerate with: make deps", file=sys.stderr)
                rc = 1
        if rc == 0:
            print("[gen-requirements] clean — locks fully pinned + hashed, direct deps match pyproject.toml")
        return rc

    # Default: regenerate. Write .in transiently, compile, then remove them so
    # the repo never carries .in files (which would trip Dependabot's
    # pip-compile detection).
    for name, content in in_contents(runtime_deps, dev_deps).items():
        (root / name).write_text(content, encoding="utf-8")
    try:
        _compile(root)
    finally:
        for name in (RUNTIME_IN, DEV_IN):
            try:
                (root / name).unlink()
            except FileNotFoundError:
                pass
    _guard_runtime_hashes(root)
    print("[gen-requirements] wrote --require-hashes guard to the runtime lock")
    return 0


# --- embedded fixtures (no network, no pip-compile) -------------------------
def _selftest() -> int:
    fail = 0

    def check(cond: bool, msg: str) -> None:
        nonlocal fail
        if not cond:
            print(f"[gen-requirements] selftest FAIL: {msg}")
            fail += 1

    # 1. deps + .in derivation.
    py = {
        "project": {
            "dependencies": ["fastapi==1.0.0", "uvicorn[standard]==2.0.0"],
            "optional-dependencies": {"dev": ["pytest==9.0.0", "ruff==0.9.0"]},
        }
    }
    runtime, dev = deps(py)
    check(runtime == ["fastapi==1.0.0", "uvicorn[standard]==2.0.0"], "runtime deps wrong")
    check(dev == ["pytest==9.0.0", "ruff==0.9.0"], "dev deps wrong")
    ins = in_contents(runtime, dev)
    check("-c requirements-runtime.lock" in ins[DEV_IN], "dev .in missing -c constraint")

    # 2. direct_specs (single-line and multi-line # via forms).
    runtime_lock = (
        "--require-hashes\n"
        "#\n"
        "# This file is autogenerated by pip-compile with Python 3.12\n"
        "#\n"
        "anyio==4.0.0 \\\n    --hash=sha256:abcd\n    # via fastapi\n"
        "fastapi==1.0.0 \\\n    --hash=sha256:abcd\n    # via -r requirements-runtime.in\n"
        "uvicorn[standard]==2.0.0 \\\n    --hash=sha256:abcd\n    # via -r requirements-runtime.in\n"
    )
    check(
        direct_specs(runtime_lock, RUNTIME_IN) == ["fastapi==1.0.0", "uvicorn[standard]==2.0.0"],
        "runtime direct_specs wrong",
    )
    dev_lock = (
        "#\n# This file is autogenerated by pip-compile with Python 3.12\n#\n"
        "pluggy==1.0.0 \\\n    --hash=sha256:abcd\n    # via pytest\n"
        "pytest==9.0.0 \\\n    --hash=sha256:abcd\n    # via\n    #   -r requirements-dev.in\n    #   pytest-asyncio\n"
        "ruff==0.9.0 \\\n    --hash=sha256:abcd\n    # via -r requirements-dev.in\n"
    )
    check(
        direct_specs(dev_lock, DEV_IN) == ["pytest==9.0.0", "ruff==0.9.0"],
        "dev direct_specs wrong (multi-line # via)",
    )

    # 3. norm handles PyYAML -> pyyaml case folding and extra-stripping.
    check(norm("PyYAML==6.0.3") == norm("pyyaml==6.0.3"), "norm case-fold wrong")
    check(norm("httpx[http2]==0.28.1") == norm("httpx==0.28.1"), "norm extra-strip wrong")

    # 4. structural checks.
    good_lock = (
        "--require-hashes\n"
        "# This file is autogenerated by pip-compile with Python 3.12\n"
        "fastapi==1.0.0 \\\n    --hash=sha256:abcd\n"
    )
    check(pinned_issues(good_lock, RUNTIME_LOCK) == [], "valid lock flagged")
    check(
        "unpinned requirement" in "\n".join(pinned_issues("fastapi>=1.0.0\n", RUNTIME_LOCK)),
        "unpinned requirement not flagged",
    )
    check(
        any("missing --require-hashes" in i for i in pinned_issues("fastapi==1.0.0\n", RUNTIME_LOCK)),
        "missing --require-hashes not flagged",
    )
    # dev lock is hash-verified but not --require-hashes-guarded (it pins
    # pip/setuptools via --allow-unsafe), so its absence there is not drift.
    check(
        not any("missing --require-hashes" in i for i in pinned_issues("fastapi==1.0.0\n", DEV_LOCK)),
        "dev lock incorrectly requires --require-hashes",
    )

    # 5. offline --check end-to-end.
    with tempfile.TemporaryDirectory(prefix="gen-req-") as tmp:
        root = Path(tmp)
        (root / "pyproject.toml").write_text(
            "[project]\n"
            'dependencies = ["fastapi==1.0.0", "uvicorn[standard]==2.0.0"]\n'
            "[project.optional-dependencies]\n"
            'dev = ["pytest==9.0.0", "ruff==0.9.0"]\n',
            encoding="utf-8",
        )
        (root / RUNTIME_LOCK).write_text(runtime_lock, encoding="utf-8")
        (root / DEV_LOCK).write_text(dev_lock, encoding="utf-8")
        check(main(["--root", str(root), "--check"]) == 0, "--check failed on a clean tree")

        # Add a dep to pyproject without regenerating -> direct deps drift.
        (root / "pyproject.toml").write_text(
            "[project]\n"
            'dependencies = ["fastapi==1.0.0", "uvicorn[standard]==2.0.0", "httpx==0.28.1"]\n'
            "[project.optional-dependencies]\n"
            'dev = ["pytest==9.0.0", "ruff==0.9.0"]\n',
            encoding="utf-8",
        )
        check(main(["--root", str(root), "--check"]) == 1, "--check passed on drifted direct deps")

        # Unpin a lock -> --check exit 1.
        (root / "pyproject.toml").write_text(
            "[project]\n"
            'dependencies = ["fastapi==1.0.0", "uvicorn[standard]==2.0.0"]\n'
            "[project.optional-dependencies]\n"
            'dev = ["pytest==9.0.0", "ruff==0.9.0"]\n',
            encoding="utf-8",
        )
        (root / RUNTIME_LOCK).write_text("--require-hashes\nfastapi>=1.0.0\n", encoding="utf-8")
        check(main(["--root", str(root), "--check"]) == 1, "--check passed on an unpinned lock")

        # Missing pyproject -> exit 2.
        check(main(["--root", str(root / "nope"), "--check"]) == 2, "missing pyproject did not exit 2")

    if fail == 0:
        print("[gen-requirements] selftest PASS")
        return 0
    print(f"[gen-requirements] selftest FAIL ({fail} check(s))")
    return 1


if __name__ == "__main__":
    sys.exit(main())
