#!/usr/bin/env python3
"""Generate requirements-{runtime,dev}.lock from pyproject.toml.

pyproject.toml is the single source of truth for what the project needs
(CI installs straight from it with `pip install -e ".[dev]"`). The two lock
files are DERIVED artifacts — never hand-edited, always regenerated here:

    requirements-runtime.lock  <- [project].dependencies
                                  (installed by the Dockerfile so the runtime
                                   image carries no dev tooling)
    requirements-dev.lock      <- [project.optional-dependencies].dev

Both are kept in lock-step with pyproject.toml by `--check`, which CI and
`make lint` run so a hand-edited or stale lock can never ship silently.

Usage:
    python scripts/gen-requirements.py              # (re)write both lock files
    python scripts/gen-requirements.py --check      # exit 1 if either is stale
    python scripts/gen-requirements.py --selftest   # run embedded fixtures
    python scripts/gen-requirements.py --root DIR   # operate on DIR (tests/CI)

Exit: 0 ok, 1 stale/out-of-date (--check) or selftest failure, 2 config error.
"""

from __future__ import annotations

import argparse
import difflib
import sys
import tempfile
import tomllib
from pathlib import Path

RUNTIME_LOCK = "requirements-runtime.lock"
DEV_LOCK = "requirements-dev.lock"

RUNTIME_HEADER = (
    "# GENERATED by scripts/gen-requirements.py — do not edit by hand.\n"
    "# Source of truth: pyproject.toml [project].dependencies (runtime only).\n"
    "# The Dockerfile installs this lock so the runtime image carries no dev tooling.\n"
)
DEV_HEADER = (
    "# GENERATED by scripts/gen-requirements.py — do not edit by hand.\n"
    "# Source of truth: pyproject.toml [project.optional-dependencies].dev.\n"
)


def render(pyproject: dict) -> dict[str, str]:
    """Map lock filename -> rendered content for a parsed pyproject dict."""
    project = pyproject["project"]
    runtime = list(project.get("dependencies", []))
    dev = list((project.get("optional-dependencies") or {}).get("dev", []))
    return {
        RUNTIME_LOCK: RUNTIME_HEADER + "".join(f"{d}\n" for d in runtime),
        DEV_LOCK: DEV_HEADER + "".join(f"{d}\n" for d in dev),
    }


def read_pyproject(root: Path) -> dict:
    path = root / "pyproject.toml"
    if not path.exists():
        raise FileNotFoundError(f"{path} not found")
    with open(path, "rb") as fh:
        return tomllib.load(fh)


def _diff(actual: str, expected: str, name: str) -> str:
    return "\n".join(
        difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=f"a/{name}",
            tofile=f"b/{name}",
            lineterm="",
        )
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if locks are stale")
    parser.add_argument("--selftest", action="store_true", help="run embedded fixtures")
    parser.add_argument("--root", type=Path, default=None, help="repo root override")
    args = parser.parse_args(argv)

    if args.selftest:
        return _selftest()

    root = (args.root or Path(__file__).resolve().parents[1]).resolve()
    try:
        pyproject = read_pyproject(root)
    except FileNotFoundError as e:
        print(f"[gen-requirements] FAIL: {e}", file=sys.stderr)
        return 2

    expected = render(pyproject)
    if args.check:
        rc = 0
        for name, content in expected.items():
            path = root / name
            if not path.exists():
                print(
                    f"[gen-requirements] FAIL: {name} missing — run scripts/gen-requirements.py",
                    file=sys.stderr,
                )
                rc = 1
                continue
            actual = path.read_text(encoding="utf-8")
            if actual != content:
                print(f"[gen-requirements] FAIL: {name} is stale:", file=sys.stderr)
                print(_diff(actual, content, name), file=sys.stderr)
                print(
                    "  -> regenerate with: python scripts/gen-requirements.py",
                    file=sys.stderr,
                )
                rc = 1
        if rc == 0:
            print("[gen-requirements] clean — lock files match pyproject.toml")
        return rc

    for name, content in expected.items():
        (root / name).write_text(content, encoding="utf-8")
        print(f"[gen-requirements] wrote {name}")
    return 0


def _selftest() -> int:
    fail = 0

    def check(cond: bool, msg: str) -> None:
        nonlocal fail
        if not cond:
            print(f"[gen-requirements] selftest FAIL: {msg}")
            fail += 1

    with tempfile.TemporaryDirectory(prefix="gen-req-") as tmp:
        root = Path(tmp)
        (root / "pyproject.toml").write_text(
            "[project]\n"
            'dependencies = ["fastapi==1.0.0", "uvicorn[standard]==2.0.0"]\n'
            "[project.optional-dependencies]\n"
            'dev = ["pytest==9.0.0", "ruff==0.9.0"]\n',
            encoding="utf-8",
        )

        expected = render(read_pyproject(root))
        check(
            expected[RUNTIME_LOCK].splitlines()[3:] == ["fastapi==1.0.0", "uvicorn[standard]==2.0.0"],
            "runtime lock content wrong",
        )
        check(
            expected[DEV_LOCK].splitlines()[2:] == ["pytest==9.0.0", "ruff==0.9.0"],
            "dev lock content wrong",
        )
        check(
            "do not edit by hand" in expected[RUNTIME_LOCK] and "do not edit by hand" in expected[DEV_LOCK],
            "generated header missing",
        )

        # Write via the normal code path, then --check must pass.
        for name, content in expected.items():
            (root / name).write_text(content, encoding="utf-8")
        check(main(["--root", str(root), "--check"]) == 0, "--check failed on freshly generated locks")

        # Mutate one lock; --check must fail (exit 1).
        (root / DEV_LOCK).write_text("# hand-edited\npytest==9.0.0\nruff==0.9.0\n", encoding="utf-8")
        check(main(["--root", str(root), "--check"]) == 1, "--check passed on a stale lock")

        # Missing lock -> --check exit 1.
        (root / DEV_LOCK).unlink()
        check(main(["--root", str(root), "--check"]) == 1, "--check passed on a missing lock")

        # Missing pyproject -> exit 2.
        check(main(["--root", str(root / "nope"), "--check"]) == 2, "missing pyproject did not exit 2")

    if fail == 0:
        print("[gen-requirements] selftest PASS")
        return 0
    print(f"[gen-requirements] selftest FAIL ({fail} check(s))")
    return 1


if __name__ == "__main__":
    sys.exit(main())
